using MegaCrit.Sts2.Core.Models;
using TogawaSakiko.NativeCode.Models.Cards;
using TogawaSakiko.NativeCode.Models.Characters;
using TogawaSakiko.NativeCode.Models.Modifiers;
using TogawaSakiko.NativeCode.Models.Potions;
using TogawaSakiko.NativeCode.Models.Pools;
using TogawaSakiko.NativeCode.Models.Powers;
using TogawaSakiko.NativeCode.Models.Relics;

namespace TogawaSakiko.NativeCode.Content;

internal static class NativeStableIds
{
    public const string EntryPrefix = "TOGAWASAKIKO-";

    public static readonly IReadOnlyDictionary<Type, string> Entries = new Dictionary<Type, string>
    {
        [typeof(Models.Characters.TogawaSakiko)] = EntryPrefix + "TOGAWA_SAKIKO",
        [typeof(TogawaSakikoCardPool)] = EntryPrefix + "TOGAWA_SAKIKO_CARD_POOL",
        [typeof(TogawaSakikoRelicPool)] = EntryPrefix + "TOGAWA_SAKIKO_RELIC_POOL",
        [typeof(TogawaSakikoPotionPool)] = EntryPrefix + "TOGAWA_SAKIKO_POTION_POOL",
        [typeof(Models.Events.OceanOfMemories)] = Models.Events.OceanOfMemories.Entry,
        [typeof(StrikeTogawaSakiko)] = EntryPrefix + "STRIKE_TOGAWA_SAKIKO",
        [typeof(DefendTogawaSakiko)] = EntryPrefix + "DEFEND_TOGAWA_SAKIKO",
        [typeof(TheMoonlightSonataCard)] = EntryPrefix + "THE_MOONLIGHT_SONATA_CARD",
        [typeof(ASplitMomentCard)] = EntryPrefix + "A_SPLIT_MOMENT_CARD",
        [typeof(DesireCard)] = EntryPrefix + "DESIRE_CARD",
        [typeof(TwoMoonsCard)] = EntryPrefix + "TWO_MOONS_CARD",
        [typeof(SilentFarewellCard)] = EntryPrefix + "SILENT_FAREWELL_CARD",
        [typeof(GreetingsCard)] = EntryPrefix + "GREETINGS_CARD",
        [typeof(TirednessCard)] = EntryPrefix + "TIREDNESS_CARD",
        [typeof(MelodyCard)] = EntryPrefix + "MELODY_CARD",
        [typeof(IdealCard)] = EntryPrefix + "IDEAL_CARD",
        [typeof(ProtectionCard)] = EntryPrefix + "PROTECTION_CARD",
        [typeof(RadianceCard)] = EntryPrefix + "RADIANCE_CARD",
        [typeof(KindnessCard)] = EntryPrefix + "KINDNESS_CARD",
        [typeof(AmorisCard)] = EntryPrefix + "AMORIS_CARD",
        [typeof(DolorisCard)] = EntryPrefix + "DOLORIS_CARD",
        [typeof(MortisCard)] = EntryPrefix + "MORTIS_CARD",
        [typeof(OblivionisCard)] = EntryPrefix + "OBLIVIONIS_CARD",
        [typeof(TimorisCard)] = EntryPrefix + "TIMORIS_CARD",
        [typeof(BlackKeysCard)] = EntryPrefix + "BLACK_KEYS_CARD",
        [typeof(WhiteKeysCard)] = EntryPrefix + "WHITE_KEYS_CARD",
        [typeof(BlackAndWhiteKeysCard)] = EntryPrefix + "BLACK_AND_WHITE_KEYS_CARD",
        [typeof(VoiceCard)] = EntryPrefix + "VOICE_CARD",
        [typeof(InnerCryCard)] = EntryPrefix + "INNER_CRY_CARD",
        [typeof(MementoMoriCard)] = EntryPrefix + "MEMENTO_MORI_CARD",
        [typeof(BudgetBentoCard)] = EntryPrefix + "BUDGET_BENTO_CARD",
        [typeof(PhantomOfSakikoCard)] = EntryPrefix + "PHANTOM_OF_SAKIKO_CARD",
        [typeof(PhantomOfTakiCard)] = EntryPrefix + "PHANTOM_OF_TAKI_CARD",
        [typeof(PhantomOfTomoriCard)] = EntryPrefix + "PHANTOM_OF_TOMORI_CARD",
        [typeof(SymbolIIAirCard)] = EntryPrefix + "SYMBOL_II_AIR_CARD",
        [typeof(DarkHeavenCard)] = EntryPrefix + "DARK_HEAVEN_CARD",
        [typeof(GeorgetteMeGeorgetteYouCard)] = EntryPrefix + "GEORGETTE_ME_GEORGETTE_YOU_CARD",
        [typeof(HeartsBarrierCard)] = EntryPrefix + "HEARTS_BARRIER_CARD",
        [typeof(DatenCard)] = EntryPrefix + "DATEN_CARD",
        [typeof(KillKiSSCard)] = EntryPrefix + "KILL_KI_SS_CARD",
        [typeof(SymbolIVEarthCard)] = EntryPrefix + "SYMBOL_IV_EARTH_CARD",
        [typeof(QuaerereLuminaCard)] = EntryPrefix + "QUAERERE_LUMINA_CARD",
        [typeof(KingsCard)] = EntryPrefix + "KINGS_CARD",
        [typeof(AccompliceCard)] = EntryPrefix + "ACCOMPLICE_CARD",
        [typeof(CarefreeCard)] = EntryPrefix + "CAREFREE_CARD",
        [typeof(DesuWaCard)] = EntryPrefix + "DESU_WA_CARD",
        [typeof(EdgeOfBreakdownCard)] = EntryPrefix + "EDGE_OF_BREAKDOWN_CARD",
        [typeof(MasqueradeRhapsodyRequestCard)] = EntryPrefix + "MASQUERADE_RHAPSODY_REQUEST_CARD",
        [typeof(WeaknessCard)] = EntryPrefix + "WEAKNESS_CARD",
        [typeof(ClockOutCard)] = EntryPrefix + "CLOCK_OUT_CARD",
        [typeof(FallenFlowersCard)] = EntryPrefix + "FALLEN_FLOWERS_CARD",
        [typeof(HachibouseiDanceCard)] = EntryPrefix + "HACHIBOUSEI_DANCE_CARD",
        [typeof(PhantomOfMutsumiCard)] = EntryPrefix + "PHANTOM_OF_MUTSUMI_CARD",
        [typeof(PhantomOfSoyoCard)] = EntryPrefix + "PHANTOM_OF_SOYO_CARD",
        [typeof(RhinocerosBeetleCard)] = EntryPrefix + "RHINOCEROS_BEETLE_CARD",
        [typeof(CountingStarsCard)] = EntryPrefix + "COUNTING_STARS_CARD",
        [typeof(AleaIactaEstCard)] = EntryPrefix + "ALEA_IACTA_EST_CARD",
        [typeof(AnglesCard)] = EntryPrefix + "ANGLES_CARD",
        [typeof(ChoirSChoirCard)] = EntryPrefix + "CHOIR_S_CHOIR_CARD",
        [typeof(CrucifixXCard)] = EntryPrefix + "CRUCIFIX_X_CARD",
        [typeof(CuriosityCard)] = EntryPrefix + "CURIOSITY_CARD",
        [typeof(EnduranceCard)] = EntryPrefix + "ENDURANCE_CARD",
        [typeof(FearlessCard)] = EntryPrefix + "FEARLESS_CARD",
        [typeof(KaoCard)] = EntryPrefix + "KAO_CARD",
        [typeof(OurSongCard)] = EntryPrefix + "OUR_SONG_CARD",
        [typeof(PerdereOmniaCard)] = EntryPrefix + "PERDERE_OMNIA_CARD",
        [typeof(PrimoDieInScaenaCard)] = EntryPrefix + "PRIMO_DIE_IN_SCAENA_CARD",
        [typeof(SeizeTheFateCard)] = EntryPrefix + "SEIZE_THE_FATE_CARD",
        [typeof(SharedDestinyCard)] = EntryPrefix + "SHARED_DESTINY_CARD",
        [typeof(SymbolIFireCard)] = EntryPrefix + "SYMBOL_I_FIRE_CARD",
        [typeof(SymbolIIIWaterCard)] = EntryPrefix + "SYMBOL_II_I_WATER_CARD",
        [typeof(TheGirlWithFlaxenHairCard)] = EntryPrefix + "THE_GIRL_WITH_FLAXEN_HAIR_CARD",
        [typeof(UtopiaCard)] = EntryPrefix + "UTOPIA_CARD",
        [typeof(VeritasCard)] = EntryPrefix + "VERITAS_CARD",
        [typeof(WishFulfilledCard)] = EntryPrefix + "WISH_FULFILLED_CARD",
        [typeof(WishToBecomeHumanCard)] = EntryPrefix + "WISH_TO_BECOME_HUMAN_CARD",
        [typeof(AsYourHeartDesiresCard)] = EntryPrefix + "AS_YOUR_HEART_DESIRES_CARD",
        [typeof(AveMujicaCard)] = EntryPrefix + "AVE_MUJICA_CARD",
        [typeof(BandInvitationCard)] = EntryPrefix + "BAND_INVITATION_CARD",
        [typeof(BlackBirthdayCard)] = EntryPrefix + "BLACK_BIRTHDAY_CARD",
        [typeof(CharismaticFormCard)] = EntryPrefix + "CHARISMATIC_FORM_CARD",
        [typeof(CrueltyCard)] = EntryPrefix + "CRUELTY_CARD",
        [typeof(CrychicCard)] = EntryPrefix + "CRYCHIC_CARD",
        [typeof(EtherCard)] = EntryPrefix + "ETHER_CARD",
        [typeof(ImprisonedXIICard)] = EntryPrefix + "IMPRISONED_XI_I_CARD",
        [typeof(MasksCard)] = EntryPrefix + "MASKS_CARD",
        [typeof(PerfectionCard)] = EntryPrefix + "PERFECTION_CARD",
        [typeof(PrideCard)] = EntryPrefix + "PRIDE_CARD",
        [typeof(SoraNoMusicaCard)] = EntryPrefix + "SORA_NO_MUSICA_CARD",
        [typeof(SpringSunlightCard)] = EntryPrefix + "SPRING_SUNLIGHT_CARD",
        [typeof(StayEleganceCard)] = EntryPrefix + "STAY_ELEGANCE_CARD",
        [typeof(WishYouGoodLuckCard)] = EntryPrefix + "WISH_YOU_GOOD_LUCK_CARD",
        [typeof(WorldviewCard)] = EntryPrefix + "WORLDVIEW_CARD",
        [typeof(DazzlingPower)] = EntryPrefix + "DAZZLING_POWER",
        [typeof(HypePower)] = EntryPrefix + "HYPE_POWER",
        [typeof(DolorisPower)] = EntryPrefix + "DOLORIS_POWER",
        [typeof(MortisPower)] = EntryPrefix + "MORTIS_POWER",
        [typeof(OblivionisPower)] = EntryPrefix + "OBLIVIONIS_POWER",
        [typeof(TimorisPower)] = EntryPrefix + "TIMORIS_POWER",
        [typeof(MelodiaPower)] = EntryPrefix + "MELODIA_POWER",
        [typeof(MonsterDivinityPower)] = EntryPrefix + "MONSTER_DIVINITY_POWER",
        [typeof(KingsPower)] = EntryPrefix + "KINGS_POWER",
        [typeof(CuriosityPower)] = EntryPrefix + "CURIOSITY_POWER",
        [typeof(EndurancePower)] = EntryPrefix + "ENDURANCE_POWER",
        [typeof(FearlessPower)] = EntryPrefix + "FEARLESS_POWER",
        [typeof(GodsCreationPower)] = EntryPrefix + "GODS_CREATION_POWER",
        [typeof(GirlOfSpringPower)] = EntryPrefix + "GIRL_OF_SPRING_POWER",
        [typeof(OurSongPower)] = EntryPrefix + "OUR_SONG_POWER",
        [typeof(PerdereOmniaPower)] = EntryPrefix + "PERDERE_OMNIA_POWER",
        [typeof(PrimoDieInScaenaPower)] = EntryPrefix + "PRIMO_DIE_IN_SCAENA_POWER",
        [typeof(SeizeTheFatePower)] = EntryPrefix + "SEIZE_THE_FATE_POWER",
        [typeof(SharedDestinyPower)] = EntryPrefix + "SHARED_DESTINY_POWER",
        [typeof(CharismaticFormPower)] = EntryPrefix + "CHARISMATIC_FORM_POWER",
        [typeof(CrueltyPower)] = EntryPrefix + "CRUELTY_POWER",
        [typeof(CrychicPower)] = EntryPrefix + "CRYCHIC_POWER",
        [typeof(PridePower)] = EntryPrefix + "PRIDE_POWER",
        [typeof(WishYouGoodLuckPower)] = EntryPrefix + "WISH_YOU_GOOD_LUCK_POWER",
        [typeof(WorldviewPower)] = EntryPrefix + "WORLDVIEW_POWER",
        [typeof(DazzlingDownPower)] = EntryPrefix + "DAZZLING_DOWN_POWER",
        [typeof(FreshlySqueezedCucumberPower)] = EntryPrefix + "FRESHLY_SQUEEZED_CUCUMBER_POWER",
        [typeof(Tracking.PowerChangeLedgerHookModel)] = EntryPrefix + "POWER_CHANGE_LEDGER_HOOK_MODEL",
        [typeof(KingsRewardCarrierModifier)] = EntryPrefix + "KINGS_REWARD_CARRIER_MODIFIER",
        [typeof(StarterRelicTogawaSakiko)] = EntryPrefix + "STARTER_RELIC_TOGAWA_SAKIKO",
        [typeof(BlazingHairband)] = EntryPrefix + "BLAZING_HAIRBAND",
        [typeof(AnotherMask)] = EntryPrefix + "ANOTHER_MASK",
        [typeof(ColorfulNotebook)] = EntryPrefix + "COLORFUL_NOTEBOOK",
        [typeof(CuteAnimalBandAid)] = EntryPrefix + "CUTE_ANIMAL_BAND_AID",
        [typeof(FountainDrink)] = EntryPrefix + "FOUNTAIN_DRINK",
        [typeof(GoldenPocketWatch)] = EntryPrefix + "GOLDEN_POCKET_WATCH",
        [typeof(MasqueradeMask)] = EntryPrefix + "MASQUERADE_MASK",
        [typeof(TheCompass)] = EntryPrefix + "THE_COMPASS",
        [typeof(TheDoll)] = EntryPrefix + "THE_DOLL",
        [typeof(TheThirdMovement)] = EntryPrefix + "THE_THIRD_MOVEMENT",
        [typeof(WarmthInfusedPorcelainCup)] = EntryPrefix + "WARMTH_INFUSED_PORCELAIN_CUP",
        [typeof(ChocolateMilkJelly)] = EntryPrefix + "CHOCOLATE_MILK_JELLY",
        [typeof(EarlGreyTea)] = EntryPrefix + "EARL_GREY_TEA",
        [typeof(FreshlySqueezedCucumber)] = EntryPrefix + "FRESHLY_SQUEEZED_CUCUMBER",
        [typeof(HallucinationPotion)] = EntryPrefix + "HALLUCINATION_POTION",
        [typeof(MatchaParfait)] = EntryPrefix + "MATCHA_PARFAIT",
        [typeof(OrangeMilkJelly)] = EntryPrefix + "ORANGE_MILK_JELLY"
    };

    public static bool IsOwnedModel(Type type)
    {
        return type.Assembly == typeof(NativeStableIds).Assembly &&
               type.IsSubclassOf(typeof(AbstractModel));
    }
}
